"""add org_settings clause_checklists sample_templates tables

Revision ID: 35a49ddb7794
Revises: f70f4dcfa2b0
Create Date: 2026-08-07 21:04:04.643305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a49ddb7794'
down_revision: Union[str, None] = 'f70f4dcfa2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clause_checklists',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('sub_id', sa.String(), nullable=False),
    sa.Column('checklist_text', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'sub_id')
    )
    op.create_table('org_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_llm_provider', sa.String(), nullable=False),
    sa.Column('default_ollama_model', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sample_templates',
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('platform')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_templates')
    op.drop_table('org_settings')
    op.drop_table('clause_checklists')
    # ### end Alembic commands ###
